export interface SpellPanel {
    //header
    spellCastingClass: string;
    spellCastingAbility: string;
    spellSaveDC: string;
    spellAttackBonus: string;
    //cantrips
    cantripOne: string;
    cantripTwo: string;
    cantripThree: string;
    cantripFour: string;
    cantripFive: string;
    cantripSix: string;
    cantripSeven: string;
    cantripEight: string;

    //level one spells
    l1SpellSlotTotal: string;
    l1SpellSlotExpended: string;
    l1Slot1:string;
    l1Slot2:string;
    l1Slot3:string;
    l1Slot4:string;
    l1Slot5:string;
    l1Slot6:string;
    l1Slot7:string;
    l1Slot8:string;
    l1Slot9:string;
    l1Slot10:string;
    l1Slot11:string;
    l1Slot12:string;
    l1Slot1Tick:boolean;
    l1Slot2Tick:boolean;
    l1Slot3Tick:boolean;
    l1Slot4Tick:boolean;
    l1Slot5Tick:boolean;
    l1Slot6Tick:boolean;
    l1Slot7Tick:boolean;
    l1Slot8Tick:boolean;
    l1Slot9Tick:boolean;
    l1Slot10Tick:boolean;
    l1Slot11Tick:boolean;
    l1Slot12Tick:boolean;

     //level two spells
     l2SpellSlotTotal: string;
     l2SpellSlotExpended: string;
     l2Slot1:string;
     l2Slot2:string;
     l2Slot3:string;
     l2Slot4:string;
     l2Slot5:string;
     l2Slot6:string;
     l2Slot7:string;
     l2Slot8:string;
     l2Slot9:string;
     l2Slot10:string;
     l2Slot11:string;
     l2Slot12:string;
     l2Slot1Tick:boolean;
     l2Slot2Tick:boolean;
     l2Slot3Tick:boolean;
     l2Slot4Tick:boolean;
     l2Slot5Tick:boolean;
     l2Slot6Tick:boolean;
     l2Slot7Tick:boolean;
     l2Slot8Tick:boolean;
     l2Slot9Tick:boolean;
     l2Slot10Tick:boolean;
     l2Slot11Tick:boolean;
     l2Slot12Tick:boolean;

      //level Three spells
    l3SpellSlotTotal: string;
    l3SpellSlotExpended: string;
    l3Slot1:string;
    l3Slot2:string;
    l3Slot3:string;
    l3Slot4:string;
    l3Slot5:string;
    l3Slot6:string;
    l3Slot7:string;
    l3Slot8:string;
    l3Slot9:string;
    l3Slot10:string;
    l3Slot11:string;
    l3Slot12:string;
    l3Slot1Tick:boolean;
    l3Slot2Tick:boolean;
    l3Slot3Tick:boolean;
    l3Slot4Tick:boolean;
    l3Slot5Tick:boolean;
    l3Slot6Tick:boolean;
    l3Slot7Tick:boolean;
    l3Slot8Tick:boolean;
    l3Slot9Tick:boolean;
    l3Slot10Tick:boolean;
    l3Slot11Tick:boolean;
    l3Slot12Tick:boolean;

     //level four spells
     l4SpellSlotTotal: string;
     l4SpellSlotExpended: string;
     l4Slot1:string;
     l4Slot2:string;
     l4Slot3:string;
     l4Slot4:string;
     l4Slot5:string;
     l4Slot6:string;
     l4Slot7:string;
     l4Slot8:string;
     l4Slot9:string;
     l4Slot10:string;
     l4Slot11:string;
     l4Slot12:string;
     l4Slot1Tick:boolean;
     l4Slot2Tick:boolean;
     l4Slot3Tick:boolean;
     l4Slot4Tick:boolean;
     l4Slot5Tick:boolean;
     l4Slot6Tick:boolean;
     l4Slot7Tick:boolean;
     l4Slot8Tick:boolean;
     l4Slot9Tick:boolean;
     l4Slot10Tick:boolean;
     l4Slot11Tick:boolean;
     l4Slot12Tick:boolean;

      //level five spells
    l5SpellSlotTotal: string;
    l5SpellSlotExpended: string;
    l5Slot1:string;
    l5Slot2:string;
    l5Slot3:string;
    l5Slot4:string;
    l5Slot5:string;
    l5Slot6:string;
    l5Slot7:string;
    l5Slot8:string;
    l5Slot9:string;
    l5Slot10:string;
    l5Slot11:string;
    l5Slot12:string;
    l5Slot1Tick:boolean;
    l5Slot2Tick:boolean;
    l5Slot3Tick:boolean;
    l5Slot4Tick:boolean;
    l5Slot5Tick:boolean;
    l5Slot6Tick:boolean;
    l5Slot7Tick:boolean;
    l5Slot8Tick:boolean;
    l5Slot9Tick:boolean;
    l5Slot10Tick:boolean;
    l5Slot11Tick:boolean;
    l5Slot12Tick:boolean;

     //level six spells
     l6SpellSlotTotal: string;
     l6SpellSlotExpended: string;
     l6Slot1:string;
     l6Slot2:string;
     l6Slot3:string;
     l6Slot4:string;
     l6Slot5:string;
     l6Slot6:string;
     l6Slot7:string;
     l6Slot8:string;
     l6Slot9:string;
     l6Slot10:string;
     l6Slot11:string;
     l6Slot12:string;
     l6Slot1Tick:boolean;
     l6Slot2Tick:boolean;
     l6Slot3Tick:boolean;
     l6Slot4Tick:boolean;
     l6Slot5Tick:boolean;
     l6Slot6Tick:boolean;
     l6Slot7Tick:boolean;
     l6Slot8Tick:boolean;
     l6Slot9Tick:boolean;
     l6Slot10Tick:boolean;
     l6Slot11Tick:boolean;
     l6Slot12Tick:boolean;

      //level seven spells
    l7SpellSlotTotal: string;
    l7SpellSlotExpended: string;
    l7Slot1:string;
    l7Slot2:string;
    l7Slot3:string;
    l7Slot4:string;
    l7Slot5:string;
    l7Slot6:string;
    l7Slot7:string;
    l7Slot8:string;
    l7Slot9:string;
    l7Slot10:string;
    l7Slot11:string;
    l7Slot12:string;
    l7Slot1Tick:boolean;
    l7Slot2Tick:boolean;
    l7Slot3Tick:boolean;
    l7Slot4Tick:boolean;
    l7Slot5Tick:boolean;
    l7Slot6Tick:boolean;
    l7Slot7Tick:boolean;
    l7Slot8Tick:boolean;
    l7Slot9Tick:boolean;
    l7Slot10Tick:boolean;
    l7Slot11Tick:boolean;
    l7Slot12Tick:boolean;

     //level eight spells
     l8SpellSlotTotal: string;
     l8SpellSlotExpended: string;
     l8Slot1:string;
     l8Slot2:string;
     l8Slot3:string;
     l8Slot4:string;
     l8Slot5:string;
     l8Slot6:string;
     l8Slot7:string;
     l8Slot8:string;
     l8Slot9:string;
     l8Slot10:string;
     l8Slot11:string;
     l8Slot12:string;
     l8Slot1Tick:boolean;
     l8Slot2Tick:boolean;
     l8Slot3Tick:boolean;
     l8Slot4Tick:boolean;
     l8Slot5Tick:boolean;
     l8Slot6Tick:boolean;
     l8Slot7Tick:boolean;
     l8Slot8Tick:boolean;
     l8Slot9Tick:boolean;
     l8Slot10Tick:boolean;
     l8Slot11Tick:boolean;
     l8Slot12Tick:boolean;

      //level nine spells
    l9SpellSlotTotal: string;
    l9SpellSlotExpended: string;
    l9Slot1:string;
    l9Slot2:string;
    l9Slot3:string;
    l9Slot4:string;
    l9Slot5:string;
    l9Slot6:string;
    l9Slot7:string;
    l9Slot8:string;
    l9Slot9:string;
    l9Slot10:string;
    l9Slot11:string;
    l9Slot12:string;
    l9Slot1Tick:boolean;
    l9Slot2Tick:boolean;
    l9Slot3Tick:boolean;
    l9Slot4Tick:boolean;
    l9Slot5Tick:boolean;
    l9Slot6Tick:boolean;
    l9Slot7Tick:boolean;
    l9Slot8Tick:boolean;
    l9Slot9Tick:boolean;
    l9Slot10Tick:boolean;
    l9Slot11Tick:boolean;
    l9Slot12Tick:boolean;

}