import { Injectable } from '@angular/core';
import { CharacterSheet } from './app/models/CharacterSheet';

@Injectable({
  providedIn: 'root'
})
export class CharacterSheetService {

  characterSheet: CharacterSheet = {
    descriptionPanel: {
      characterName: '',
      classLevel: '',
      background: '',
      playerName: '',
      faction: '',
      race: '',
      alignment: '',
      exp: 0,
      age: 0,
      height: '',
      weight:  '',
      eyes:  '',
      skin:  '',
      hair:  ''
    },
    statPanel: {
      strength: 0,
      dexterity: 0,
      constitution: 0,
      intelligence: 0,
      wisdom: 0,
      charisma: 0,
    },
    skillSavePanel: {
      inspiration: 0,
      proficiencyBonus: 0,
      strengthSave: 0,
      dexteritySave: 0,
      constitutionSave: 0,
      intelligenceSave: 0,
      wisdomSave: 0,
      charismaSave: 0,
      strengthTick: false,
      dexterityTick: false,
      constitutionTick: false,
      intelligenceTick: false,
      wisdomTick: false,
      charismaTick: false
    },
    skillPanel: {
      acrobatics: 0,
      animalHandling: 0,
      arcana: 0,
      athletics: 0,
      deception: 0,
      history: 0,
      insight: 0,
      intimidation: 0,
      investigation: 0,
      medicine: 0,
      nature: 0,
      perception: 0,
      performance: 0,
      persuasion: 0,
      religion: 0,
      slightOfHand: 0,
      stealth: 0,
      survival: 0,
      acrobaticsTick: false,
      animalHandlingTick: false,
      arcanaTick: false,
      athleticsTick: false,
      deceptionTick: false,
      historyTick: false,
      insightTick: false,
      intimidationTick: false,
      investigationTick: false,
      medicineTick: false,
      natureTick: false,
      perceptionTick: false,
      performanceTick: false,
      persuasionTick: false,
      religionTick: false,
      slightOfHandTick: false,
      stealthTick: false,
      survivalTick: false
    },
    combatPanel: {
      armorClass: 0,
      initiative: 0,
      speed: 0,
      hitPointMaximum: 0,
      currentHitPoints: 0,
      temporaryHitPoint: 0,
      hitDie: ''
    },
    attackPanel: {
      attackOne: '',
      attackBonusOne: '',
      attackTypeOne: '',
      attackTwo: '',
      attackBonusTwo: '',
      attackTypeTwo: '',
      attackThree: '',
      attackBonusThree: '',
      attackTypeThree: '',
      attackFour: '',
      attackBonusFour: '',
      attackTypeFour: '',
      attackDescription: ''
    },
    personalityPanel: {
      personalityTraits: '',
      ideals: '',
      bonds: '',
      flaws: '',
    },
    equipmentPanel: {
      equipment: '',
      copperPoints: 0,
      silverPoints: 0,
      electrumPoints: 0,
      goldPoints: 0,
      platinumPoints:0
    },
    characterDetailsPanel: {
      darkGift: '',
    additionalFeaturesAndTraits: '',
    characterBackStory: '',
    alliesAndOrganizations: '',
    treasure:  '',
    },
    spellPanel: {
         //header
    spellCastingClass: '',
    spellCastingAbility: '',
    spellSaveDC: '',
    spellAttackBonus: '',
    //cantrips
    cantripOne: '',
    cantripTwo: '',
    cantripThree: '',
    cantripFour: '',
    cantripFive: '',
    cantripSix: '',
    cantripSeven: '',
    cantripEight: '',

    //level one spells
    l1SpellSlotTotal: '',
    l1SpellSlotExpended: '',
    l1Slot1:'',
    l1Slot2:'',
    l1Slot3:'',
    l1Slot4:'',
    l1Slot5:'',
    l1Slot6:'',
    l1Slot7:'',
    l1Slot8:'',
    l1Slot9:'',
    l1Slot10:'',
    l1Slot11:'',
    l1Slot12:'',
    l1Slot1Tick:false,
    l1Slot2Tick:false,
    l1Slot3Tick:false,
    l1Slot4Tick:false,
    l1Slot5Tick:false,
    l1Slot6Tick:false,
    l1Slot7Tick:false,
    l1Slot8Tick:false,
    l1Slot9Tick:false,
    l1Slot10Tick:false,
    l1Slot11Tick:false,
    l1Slot12Tick:false,

     //level two spells
     l2SpellSlotTotal: '',
     l2SpellSlotExpended: '',
     l2Slot1:'',
     l2Slot2:'',
     l2Slot3:'',
     l2Slot4:'',
     l2Slot5:'',
     l2Slot6:'',
     l2Slot7:'',
     l2Slot8:'',
     l2Slot9:'',
     l2Slot10:'',
     l2Slot11:'',
     l2Slot12:'',
     l2Slot1Tick:false,
     l2Slot2Tick:false,
     l2Slot3Tick:false,
     l2Slot4Tick:false,
     l2Slot5Tick:false,
     l2Slot6Tick:false,
     l2Slot7Tick:false,
     l2Slot8Tick:false,
     l2Slot9Tick:false,
     l2Slot10Tick:false,
     l2Slot11Tick:false,
     l2Slot12Tick:false,

      //level Three spells
    l3SpellSlotTotal: '',
    l3SpellSlotExpended: '',
    l3Slot1:'',
    l3Slot2:'',
    l3Slot3:'',
    l3Slot4:'',
    l3Slot5:'',
    l3Slot6:'',
    l3Slot7:'',
    l3Slot8:'',
    l3Slot9:'',
    l3Slot10:'',
    l3Slot11:'',
    l3Slot12:'',
    l3Slot1Tick:false,
    l3Slot2Tick:false,
    l3Slot3Tick:false,
    l3Slot4Tick:false,
    l3Slot5Tick:false,
    l3Slot6Tick:false,
    l3Slot7Tick:false,
    l3Slot8Tick:false,
    l3Slot9Tick:false,
    l3Slot10Tick:false,
    l3Slot11Tick:false,
    l3Slot12Tick:false,

     //level four spells
     l4SpellSlotTotal: '',
     l4SpellSlotExpended: '',
     l4Slot1:'',
     l4Slot2:'',
     l4Slot3:'',
     l4Slot4:'',
     l4Slot5:'',
     l4Slot6:'',
     l4Slot7:'',
     l4Slot8:'',
     l4Slot9:'',
     l4Slot10:'',
     l4Slot11:'',
     l4Slot12:'',
     l4Slot1Tick:false,
     l4Slot2Tick:false,
     l4Slot3Tick:false,
     l4Slot4Tick:false,
     l4Slot5Tick:false,
     l4Slot6Tick:false,
     l4Slot7Tick:false,
     l4Slot8Tick:false,
     l4Slot9Tick:false,
     l4Slot10Tick:false,
     l4Slot11Tick:false,
     l4Slot12Tick:false,

      //level five spells
    l5SpellSlotTotal: '',
    l5SpellSlotExpended: '',
    l5Slot1:'',
    l5Slot2:'',
    l5Slot3:'',
    l5Slot4:'',
    l5Slot5:'',
    l5Slot6:'',
    l5Slot7:'',
    l5Slot8:'',
    l5Slot9:'',
    l5Slot10:'',
    l5Slot11:'',
    l5Slot12:'',
    l5Slot1Tick:false,
    l5Slot2Tick:false,
    l5Slot3Tick:false,
    l5Slot4Tick:false,
    l5Slot5Tick:false,
    l5Slot6Tick:false,
    l5Slot7Tick:false,
    l5Slot8Tick:false,
    l5Slot9Tick:false,
    l5Slot10Tick:false,
    l5Slot11Tick:false,
    l5Slot12Tick:false,

     //level six spells
     l6SpellSlotTotal: '',
     l6SpellSlotExpended: '',
     l6Slot1:'',
     l6Slot2:'',
     l6Slot3:'',
     l6Slot4:'',
     l6Slot5:'',
     l6Slot6:'',
     l6Slot7:'',
     l6Slot8:'',
     l6Slot9:'',
     l6Slot10:'',
     l6Slot11:'',
     l6Slot12:'',
     l6Slot1Tick:false,
     l6Slot2Tick:false,
     l6Slot3Tick:false,
     l6Slot4Tick:false,
     l6Slot5Tick:false,
     l6Slot6Tick:false,
     l6Slot7Tick:false,
     l6Slot8Tick:false,
     l6Slot9Tick:false,
     l6Slot10Tick:false,
     l6Slot11Tick:false,
     l6Slot12Tick:false,

      //level seven spells
    l7SpellSlotTotal: '',
    l7SpellSlotExpended: '',
    l7Slot1:'',
    l7Slot2:'',
    l7Slot3:'',
    l7Slot4:'',
    l7Slot5:'',
    l7Slot6:'',
    l7Slot7:'',
    l7Slot8:'',
    l7Slot9:'',
    l7Slot10:'',
    l7Slot11:'',
    l7Slot12:'',
    l7Slot1Tick:false,
    l7Slot2Tick:false,
    l7Slot3Tick:false,
    l7Slot4Tick:false,
    l7Slot5Tick:false,
    l7Slot6Tick:false,
    l7Slot7Tick:false,
    l7Slot8Tick:false,
    l7Slot9Tick:false,
    l7Slot10Tick:false,
    l7Slot11Tick:false,
    l7Slot12Tick:false,

     //level eight spells
     l8SpellSlotTotal: '',
     l8SpellSlotExpended: '',
     l8Slot1:'',
     l8Slot2:'',
     l8Slot3:'',
     l8Slot4:'',
     l8Slot5:'',
     l8Slot6:'',
     l8Slot7:'',
     l8Slot8:'',
     l8Slot9:'',
     l8Slot10:'',
     l8Slot11:'',
     l8Slot12:'',
     l8Slot1Tick:false,
     l8Slot2Tick:false,
     l8Slot3Tick:false,
     l8Slot4Tick:false,
     l8Slot5Tick:false,
     l8Slot6Tick:false,
     l8Slot7Tick:false,
     l8Slot8Tick:false,
     l8Slot9Tick:false,
     l8Slot10Tick:false,
     l8Slot11Tick:false,
     l8Slot12Tick:false,

      //level nine spells
    l9SpellSlotTotal: '',
    l9SpellSlotExpended: '',
    l9Slot1:'',
    l9Slot2:'',
    l9Slot3:'',
    l9Slot4:'',
    l9Slot5:'',
    l9Slot6:'',
    l9Slot7:'',
    l9Slot8:'',
    l9Slot9:'',
    l9Slot10:'',
    l9Slot11:'',
    l9Slot12:'',
    l9Slot1Tick:false,
    l9Slot2Tick:false,
    l9Slot3Tick:false,
    l9Slot4Tick:false,
    l9Slot5Tick:false,
    l9Slot6Tick:false,
    l9Slot7Tick:false,
    l9Slot8Tick:false,
    l9Slot9Tick:false,
    l9Slot10Tick:false,
    l9Slot11Tick:false,
    l9Slot12Tick:false,
    }
  };

  constructor() { }

  printCharacter(): void {
    console.log(JSON.stringify(this.characterSheet));
  }
}
